# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcf14c0a3555f05817151329498a6ab91da00f3e1aff7733475cb09bdde67c4838d91a1d9803bc507f514153e8b65084663947757ef1eb659cb132cf24e3ef4d

test:
  secret_key_base: cba28a68cec229dbb0b86ae1ca3c622614dcea358d8d7757d218b3b9172b50e5c0f8895cb5254f6307a238b2575c0b814b81b80743ebf8773ef859b7a6603f74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
